<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => '拒绝访问',
	'Add' => '添加',
	'Add child' => '添加子项',
	'Add {type}' => '添加{type}',
	'Ancestors' => '祖先',
	'Are you sure you want to delete this item?' => '您确定要删除指定授权项？',
	'Assign' => '指派',
	'Assign permission' => '已指派的权限',
	'Assigned items' => '已指派的授权项',
	'Assignments' => '授权',
	'Business rule' => '业务逻辑',
	'Cancel' => '取消',
	'Create' => '创建',
	'Delete' => '删除',
	'Data' => '资料',
	'Descendants' => '后代',
	'Description' => '描述',
	'Edit' => '编辑',
	'Invalid request.' => '无效的请求',
	'Item does not exist.' => '授权项不存在',
	'Items' => '授权项',
	'Items assigned to this user' => '授权项已指派给用户',
	'New {type}' => '新的{type}',
	'No assignments found.' => '没有找到授权项',
	'No {type} found.' => '没有找到{type}',
	'Page not found.' => '页面未找到',
	'Permissions' => '权限',
	'Permissions granted by this item' => '此授权项的权限',
	'Permissions that inherit this item' => '此授权项继承的权限',
	'Remove' => '移除',
	'Revoke' => '撤消',
	'Save' => '储存',
	'Select item' => '选择授权项',
	'System name' => '系统名称',
	'System name cannot be changed after creation.' => '不允许更改系统名称',
	'This item does not have any ancestors.' => '此授权项并没有祖先',
	'This item does not have any descendants.' => '此授权项并没有后代',
	'This user does not have any assignments.' => '此用户并没有任何授权项',
	'Type' => '种类',
	'User' => '用户',
	'View' => '查看',
	'operation|operations' => '操作',
	'role|roles' => '角色',
	'task|tasks' => '任务',
);
