<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'Доступ запрещен.',
	'Add' => 'Добавить',
	'Add child' => 'Добавить потомка',
	'Add {type}' => 'Добавить {type}',
	'Ancestors' => 'Предки',
	'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить данный элемент?',
	'Assign' => 'Назначить',
	'Assign permission' => 'Назначить права',
	'Assigned items' => 'Назначенные элементы',
	'Assignments' => 'Соответствия',
	'Business rule' => 'Бизнес правило',
	'Cancel' => 'Отменить',
	'Create' => 'Создать',
	'Delete' => 'Удалить',
	'Data' => 'Данные',
	'Descendants' => 'Потомки',
	'Description' => 'Описание',
	'Edit' => 'Редактировать',
	'Invalid request.' => 'Неверный запрос.',
	'Item does not exist.' => 'Элемент не существует.',
	'Items' => 'Элементы',
	'Items assigned to this user' => 'Элемент назначен данному пользователю',
	'New {type}' => 'Новый {type}',
	'No assignments found.' => 'Не найдено назначений',
	'No {type} found.' => 'Не найдено {type}',
	'Page not found.' => 'Страница не найдена',
	'Permissions' => 'Права',
	'Permissions granted by this item' => 'Права, предоставляемые элементом',
	'Permissions that inherit this item' => 'Права, которые наследует данный элемент',
	'Remove' => 'Удалить',
	'Revoke' => 'Отнять',
	'Save' => 'Сохранить',
	'Select item' => 'Выбрать элемент',
	'System name' => 'Системное название',
	'System name cannot be changed after creation.' => 'Системное название не может быть изменено после создания',
	'This item does not have any ancestors.' => 'Данный элемент не имеет предков',
	'This item does not have any descendants.' => 'Данный элемент не имеет потомков',
	'This user does not have any assignments.' => 'Данный пользователь не имеет прав',
	'Type' => 'Тип',
	'User' => 'Пользователь',
	'View' => 'Просмотреть',
	'operation|operations' => 'операция|операции',
	'role|roles' => 'роль|роли',
	'task|tasks' => 'задание|задания',
);
