<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'Acceso denegado.',
	'Add' => 'Agregar',
	'Add child' => 'Agregar hijo',
	'Add {type}' => 'Agregar {type}',
	'Ancestors' => 'Ancestros',
	'Are you sure you want to delete this item?' => '¿Está seguro de querer eliminar este elemento?',
	'Assign' => 'Asignar',
	'Assign permission' => 'Asignar permiso',
	'Assigned items' => 'Elementos asignados',
	'Assignments' => 'Asignaciones',
	'Business rule' => 'Regla de negocio',
	'Cancel' => 'Cancelar',
	'Create' => 'Crear',
	'Delete' => 'Eliminar',
	'Data' => 'Datos',
	'Descendants' => 'Descendientes',
	'Description' => 'Descripción',
	'Edit' => 'Editar',
	'Invalid request.' => 'Solicitud inválida.',
	'Item does not exist.' => 'El elemento no existe.',
	'Items' => 'Elementos',
	'Items assigned to this user' => 'Elementos asignados a este usuario',
	'New {type}' => 'Nuevo {type}',
	'No assignments found.' => 'No se encontraron asignaciones.',
	'No {type} found.' => '{type} no encontrado(s).',
	'Page not found.' => 'Página no encontrada.',
	'Permissions' => 'Permisos',
	'Permissions granted by this item' => 'Permisos otorgados a este elemento',
	'Permissions that inherit this item' => 'Permisos que hereda este elemento',
	'Remove' => 'Eliminar',
	'Revoke' => 'Revocar',
	'Save' => 'Guardar',
	'Select item' => 'Seleccionar elemento',
	'System name' => 'Nombre de sistema',
	'System name cannot be changed after creation.' => 'El nombre de sistema no puede cambiarse después de crearse.',
	'This item does not have any ancestors.' => 'Este elemento no tiene ancestros.',
	'This item does not have any descendants.' => 'Este elemento no tiene descendientes.',
	'This user does not have any assignments.' => 'Este usuario no tiene asignaciones.',
	'Type' => 'Tipo',
	'User' => 'Usuario',
	'View' => 'Ver',
	'operation|operations' => 'operación|operaciones',
	'role|roles' => 'rol|roles',
	'task|tasks' => 'tarea|tareas',
);
