<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'アクセスが許可されていません。',
	'Add' => '追加',
	'Add child' => '子を追加する',
	'Add {type}' => '{type} を追加する',
	'Ancestors' => '親アイテム',
	'Are you sure you want to delete this item?' => 'このアイテムを削除します。よろしいですか？',
	'Assign' => '割り当て',
	'Assign permission' => '権限を割り当てる',
	'Assigned items' => '割り当てられたアイテム',
	'Assignments' => '割り当て',
	'Business rule' => 'ビジネスルール',
	'Cancel' => 'キャンセル',
	'Create' => '作成',
	'Delete' => '削除',
	'Data' => 'データ',
	'Descendants' => '子アイテム',
	'Description' => '説明',
	'Edit' => '編集',
	'Invalid request.' => '',
	'Item does not exist.' => 'アイテムが存在しません。',
	'Items' => 'アイテム',
	'Items assigned to this user' => 'このユーザに割り当てられたアイテム',
	'New {type}' => '新しい {type}',
	'No assignments found.' => '割り当てられたアイテムが見つかりません。',
	'No {type} found.' => '{type} が見つかりません。',
	'Page not found.' => 'ページが見つかりません。',
	'Permissions' => '権限',
	'Permissions granted by this item' => 'このアイテムによって許可される権限',
	'Permissions that inherit this item' => 'このアイテムを継承する権限',
	'Remove' => '削除',
	'Revoke' => '取り消す',
	'Save' => '保存',
	'Select item' => 'アイテムを選択してください',
	'System name' => 'システム名称',
	'System name cannot be changed after creation.' => 'システム名称は作成後に変更することは出来ません。',
	'This item does not have any ancestors.' => 'このアイテムには親がありません。',
	'This item does not have any descendants.' => 'このアイテムには子がありません。',
	'This user does not have any assignments.' => 'このユーザにはアイテムの割り当てがありません。',
	'Type' => 'タイプ',
	'User' => 'ユーザ',
	'View' => '閲覧',
	'operation|operations' => 'オペレーション',
	'role|roles' => 'ロール',
	'task|tasks' => 'タスク',
);
