<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'Accès refusé',
	'Add' => 'Ajouter',
	'Add child' => 'Ajouter enfant',
	'Add {type}' => 'Ajouter {type}',
	'Ancestors' => 'Ancêtres',
	'Are you sure you want to delete this item?' => 'Etes-vous sûr de vouloir supprimer cet item ?',
	'Assign' => 'Assigner',
	'Assign permission' => 'Assigner permission',
	'Assigned items' => 'Assigner item',
	'Assignments' => 'Assignements',
	'Business rule' => 'Règle métier',
	'Cancel' => 'Annuler',
	'Create' => 'Créer',
	'Delete' => 'Supprimer',
	'Data' => 'Donné',
	'Descendants' => 'Descendants',
	'Description' => 'Description',
	'Edit' => 'Modifier',
	'Invalid request.' => 'Requête invalide.',
	'Item does not exist.' => 'Cet item n\'existe pas',
	'Items' => 'Items',
	'Items assigned to this user' => 'Items assignés à cet utilisateur',
	'New {type}' => 'Nouveau {type}',
	'No assignments found.' => 'Aucune assignation trouvée',
	'No {type} found.' => 'Aucun(e) {type} trouvé(e)',
	'Page not found.' => 'Page introuvable',
	'Permissions' => 'Permissions',
	'Permissions granted by this item' => 'Permissions fournies par cet item',
	'Permissions that inherit this item' => 'Permissions qui héritent de cet item',
	'Remove' => 'Supprimer',
	'Revoke' => 'Revoquer',
	'Save' => 'Sauver',
	'Select item' => 'Sélectionner item',
	'System name' => 'Nom système',
	'System name cannot be changed after creation.' => 'Le nom système ne peut pas être modifié après création.',
	'This item does not have any ancestors.' => 'Cet item n\'a pas d\'ancêtre.',
	'This item does not have any descendants.' => 'Cet item n\'a pas de descendant.',
	'This user does not have any assignments.' => 'Cet utilisateur n\'a pas d\'assignation.',
	'Type' => 'Type',
	'User' => 'Utilisateur',
	'View' => 'Vue',
	'operation|operations' => 'opération|opérations',
	'role|roles' => 'rôle|rôles',
	'task|tasks' => 'tâche|tâches',
);
