<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'Acesso negado.',
	'Add' => 'Adicionar',
	'Add child' => 'Adicionar descendente',
	'Add {type}' => 'Adicionar {type}',
	'Ancestors' => 'Ancestrais',
	'Are you sure you want to delete this item?' => 'Tem certeza que deseja apagar este item?',
	'Assign' => 'Atribuir',
	'Assign permission' => 'Atribuir permissão',
	'Assigned items' => 'Itens atribuídos',
	'Assignments' => 'Atribuições',
	'Business rule' => 'Regra',
	'Cancel' => 'Cancelar',
	'Create' => 'Criar',
	'Delete' => 'Apagar',
	'Data' => 'Dados',
	'Descendants' => 'Descendentes',
	'Description' => 'Descrição',
	'Edit' => 'Editar',
	'Invalid request.' => 'Pedido inválido.',
	'Item does not exist.' => 'O item não existe.',
	'Items' => 'Itens',
	'Items assigned to this user' => 'Itens atribuídos a este usuário',
	'New {type}' => 'Novo {type}',
	'No assignments found.' => 'Atribuições não encontradas.',
	'No {type} found.' => '"{type}" Não encontrado.',
	'Page not found.' => 'Página não encontrada.',
	'Permissions' => 'Permissões',
	'Permissions granted by this item' => 'Permissões concedidas por este item',
	'Permissions that inherit this item' => 'Permissões que herdam este item',
	'Remove' => 'Remover',
	'Revoke' => 'Anular',
	'Save' => 'Salvar',
	'Select item' => 'Selecionar item',
	'System name' => 'Nome de sistema',
	'System name cannot be changed after creation.' => 'Nome de sistema não poderá ser alterado após a criação.',
	'This item does not have any ancestors.' => 'Este item não possui ancestrais.',
	'This item does not have any descendants.' => 'Este item não possui descendentes.',
	'This user does not have any assignments.' => 'Este usuário não possui atribuições.',
	'Type' => 'Tipo',
	'User' => 'Usuário',
	'View' => 'Exibir',
	'operation|operations' => 'operação|operações',
	'role|roles' => 'função|funções',
	'task|tasks' => 'tarefa|tarefas',
);