<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'Accesso negato.',
	'Add' => 'Aggiungi',
	'Add child' => 'Aggiungi come figlio',
	'Add {type}' => 'Aggiungi {type}',
	'Ancestors' => 'Antenati',
	'Are you sure you want to delete this item?' => 'Sei sicuro di voler cancellare questo elemento?',
	'Assign' => 'Associa',
	'Assign permission' => 'Associa autorizzazione',
	'Assigned items' => 'Elementi associati',
	'Assignments' => 'Incarichi',
	'Business rule' => 'Regole di attività',
	'Cancel' => 'Annulla',
	'Create' => 'Crea',
	'Delete' => 'Cancella',
	'Data' => 'Dati',
	'Descendants' => 'Discendenti',
	'Description' => 'Descrizione',
	'Edit' => 'Modifica',
	'Invalid request.' => 'Richiesta non valida.',
	'Item does not exist.' => 'L\'elemento non esiste.',
	'Items' => 'Elementi',
	'Items assigned to this user' => 'Elementi associati a questo utente',
	'New {type}' => 'Aggiungi {type}',
	'No assignments found.' => 'Nessun incarico trovato.',
	'No {type} found.' => 'Impossibile trovare {type}',
	'Page not found.' => 'Pagina non trovata.',
	'Permissions' => 'Autorizzazioni',
	'Permissions granted by this item' => 'Autorizzazioni concesse da questo elemento',
	'Permissions that inherit this item' => 'Autorizzazioni che ereditano questo elemento',
	'Remove' => 'Cancella',
	'Revoke' => 'Revoca',
	'Save' => 'Salva',
	'Select item' => 'Seleziona elemento',
	'System name' => 'Etichetta',
	'System name cannot be changed after creation.' => 'L\'etichetta non può essere cambiata una volta creata.',
	'This item does not have any ancestors.' => 'Questo elemento non ha antenati.',
	'This item does not have any descendants.' => 'Questo elemento non ha discendenti.',
	'This user does not have any assignments.' => 'Questo utente è privo incarichi.',
	'Type' => 'Tipo',
	'User' => 'Utente',
	'View' => 'Dettagli',
	'operation|operations' => 'operazione|operazioni',
	'role|roles' => 'ruolo|ruoli',
	'task|tasks' => 'compito|compiti',
);
