<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Access denied.' => 'Zugriff verweigert.',
  'Add' => 'Hinzufügen',
  'Add child' => 'Untergeordnetes Element hinzufügen',
  'Add {type}' => '{type} hinzufügen',
  'Ancestors' => 'Übergeordnete',
  'Are you sure you want to delete this item?' => '',
  'Assign' => 'Zuordnen',
  'Assign permission' => 'Berechtigung zuweisen',
  'Assigned items' => 'Zugeordnete Einträge',
  'Assignments' => 'Zuordnungen',
  'Business rule' => 'Geschäftsregel',
  'Cancel' => 'Abbrechen',
  'Create' => 'Anlegen',
  'Data' => 'Daten',
  'Descendants' => 'Untergeordnete',
  'Description' => 'Beschreibung',
  'Edit' => 'Bearbeiten',
  'Invalid request.' => 'Ungültige Anfrage.',
  'Item does not exist.' => 'Eintrag existiert nicht.',
  'Items' => 'Einträge',
  'Items assigned to this user' => 'Diesem Benutzer zugeordnete Einträge',
  'New {type}' => 'Neu {type}',
  'No assignments found.' => '',
  'No {type} found.' => '{type} nicht gefunden.',
  'Page not found.' => '',
  'Permissions' => 'Berechtigungen',
  'Permissions granted by this item' => 'Durch diesen Eintrag gewährte Berechtigungen',
  'Permissions that inherit this item' => 'Berechtigungen, die diesen Eintrag erben',
  'Remove' => 'Entfernen',
  'Revoke' => 'Zurückziehen',
  'Save' => 'Speichern',
  'Select item' => 'Eintrag auswählen',
  'System name' => 'Systemname',
  'System name cannot be changed after creation.' => '',
  'This item does not have any ancestors.' => 'Dieser Eintrag hat keine übergeordneten Einträge.',
  'This item does not have any descendants.' => 'Dieser Eintrag hat keine untergeordneten Einträge.',
  'This user does not have any assignments.' => 'Dieser Benutzer hat keine Zuordnungen.',
  'Type' => 'Typ',
  'User' => 'Benutzer',
  'View' => 'Anzeigen',
  'operation|operations' => 'operation|operationen',
  'role|roles' => 'rolle|rollen',
  'task|tasks' => 'aufgabe|aufgaben',
);
