<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'Dostęp zabroniony.',
	'Add' => 'Dodaj',
	'Add child' => 'Dodaj potomka',
	'Add {type}' => 'Dodaj {type}',
	'Ancestors' => 'Rodzice',
	'Are you sure you want to delete this item?' => 'Jesteś pewien, że chcesz usunąć ten element?',
	'Assign' => 'Przydziel',
	'Assign permission' => 'Przydziel uprawnienie',
	'Assigned items' => 'Przydzielone elementy',
	'Assignments' => 'Przydziały',
	'Business rule' => 'Reguła biznesowa',
	'Cancel' => 'Anuluj',
	'Create' => 'Utwórz',
	'Delete' => 'Usuń',
	'Data' => 'Dane',
	'Descendants' => 'Potomkowie',
	'Description' => 'Opis',
	'Edit' => 'Edytuj',
	'Invalid request.' => 'Nieprawidłowe żądanie.',
	'Item does not exist.' => 'Element nie istnieje.',
	'Items' => 'Elementy',
	'Items assigned to this user' => 'Elementy przydzielone temu użytkownikowi',
	'New {type}' => 'Nowy {type}',
	'No assignments found.' => 'Nie odnaleziono żadnych przydziałów.',
	'No {type} found.' => 'Nie odnaleziono {type}.',
	'Page not found.' => 'Strona nie odnaleziona.',
	'Permissions' => 'Uprawnienia',
	'Permissions granted by this item' => 'Uprawnienia nadane przez ten element',
	'Permissions that inherit this item' => 'Uprawnienia, które dziedziczą ten element',
	'Remove' => 'Usuń',
	'Revoke' => 'Odbierz',
	'Save' => 'Zapisz',
	'Select item' => 'Wybierz element',
	'System name' => 'Nazwa systemowa',
	'System name cannot be changed after creation.' => 'Nazwa systemowa nie może zostać zmieniona po utworzeniu',
	'This item does not have any ancestors.' => 'Ten element nie ma rodziców.',
	'This item does not have any descendants.' => 'Ten element nie ma potomków.',
	'This user does not have any assignments.' => 'Ten użytkownik nie ma żadnych przydzielonych elementów.',
	'Type' => 'Typ',
	'User' => 'Użytkownik',
	'View' => 'Obejrzyj',
	'operation|operations' => 'operacja|operacje|operacji|operacji',
	'role|roles' => 'rola|role|roli|roli',
	'task|tasks' => 'zadanie|zadania|zadań|zadania',
);
