<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => '',
	'Add' => '',
	'Add child' => '',
	'Add {type}' => '',
	'Ancestors' => '',
	'Are you sure you want to delete this item?' => '',
	'Assign' => '',
	'Assign permission' => '',
	'Assigned items' => '',
	'Assignments' => '',
	'Business rule' => '',
	'Cancel' => '',
	'Create' => '',
	'Delete' => '',
	'Data' => '',
	'Descendants' => '',
	'Description' => '',
	'Edit' => '',
	'Invalid request.' => '',
	'Item does not exist.' => '',
	'Items' => '',
	'Items assigned to this user' => '',
	'New {type}' => '',
	'No assignments found.' => '',
	'No {type} found.' => '',
	'Page not found.' => '',
	'Permissions' => '',
	'Permissions granted by this item' => '',
	'Permissions that inherit this item' => '',
	'Remove' => '',
	'Revoke' => '',
	'Save' => '',
	'Select item' => '',
	'System name' => '',
	'System name cannot be changed after creation.' => '',
	'This item does not have any ancestors.' => '',
	'This item does not have any descendants.' => '',
	'This user does not have any assignments.' => '',
	'Type' => '',
	'User' => '',
	'View' => '',
	'operation|operations' => '',
	'role|roles' => '',
	'task|tasks' => '',
);
