<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'Доступ заборонено.',
	'Add' => 'Додати',
	'Add child' => 'Додати нащадка',
	'Add {type}' => 'Додати {type}',
	'Ancestors' => 'Предки',
	'Are you sure you want to delete this item?' => 'Ви дійсно хочете видалити цей елемент?',
	'Assign' => 'Призначити',
	'Assign permission' => 'Призначити дозвіл',
	'Assigned items' => 'Призначені елементи',
	'Assignments' => 'Призначення',
	'Business rule' => 'Бізнес правило',
	'Cancel' => 'Скасувати',
	'Create' => 'Створити',
	'Delete' => 'Видалити',
	'Data' => 'Дані',
	'Descendants' => 'Нащадки',
	'Description' => 'Опис',
	'Edit' => 'Редагувати',
	'Invalid request.' => 'Некоректний запит.',
	'Item does not exist.' => 'Елемент не існує.',
	'Items' => 'Елементи',
	'Items assigned to this user' => 'Елементи призначені цьому користувачу',
	'New {type}' => 'Нова {type}',
	'No assignments found.' => 'Не знайдено призначень.',
	'No {type} found.' => 'Не знайдено {type}.',
	'Page not found.' => 'Сторінку не знайдено.',
	'Permissions' => 'Дозволи',
	'Permissions granted by this item' => 'Дозволи надані цим елементом',
	'Permissions that inherit this item' => 'Дозволи які успадковують цей елемент.',
	'Remove' => 'Видалити',
	'Revoke' => 'Відкликати',
	'Save' => 'Зберегти',
	'Select item' => 'Виберіть елемент',
	'System name' => 'Системна назва',
	'System name cannot be changed after creation.' => 'Системна назва не може бути змінена після створення.',
	'This item does not have any ancestors.' => 'Цей елемент не має предків.',
	'This item does not have any descendants.' => 'Цей елемент не має нащадків.',
	'This user does not have any assignments.' => 'Цей елемент не має призначень.',
	'Type' => 'Тип',
	'User' => 'Користувач',
	'View' => 'Перегляд',
	'operation|operations' => 'операція|операції',
	'role|roles' => 'роль|ролі',
	'task|tasks' => 'завдання|завдання',
);
