<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'Afgang nægtet.',
	'Add' => 'Tilføj',
	'Add child' => 'Tilføj barn',
	'Add {type}' => 'Tilføj {type}',
	'Ancestors' => 'Forfædre',
	'Are you sure you want to delete this item?' => 'Er du sikker på at du vil slette dette element?',
	'Assign' => 'Tildel',
	'Assign permission' => 'Tildel rettighed',
	'Assigned items' => 'Tildelte elementer',
	'Assignments' => 'Tildelinger',
	'Business rule' => 'Forretningsregel',
	'Cancel' => 'Annuller',
	'Create' => 'Opret',
	'Delete' => 'SLet',
	'Data' => 'Data',
	'Descendants' => 'Efterkommere',
	'Description' => 'Beskrivelse',
	'Edit' => 'Ret',
	'Invalid request.' => 'Ugyldig forespørgsel.',
	'Item does not exist.' => 'Elementet eksisterer ikke.',
	'Items' => 'Elementer',
	'Items assigned to this user' => 'Elementer tildelt denne bruger',
	'New {type}' => 'Ny {type}',
	'No assignments found.' => 'Ingen tildelinger fundet.',
	'No {type} found.' => 'Ingen {type} fundet.',
	'Page not found.' => 'Siden blev ikke fundet.',
	'Permissions' => 'Rettigheder',
	'Permissions granted by this item' => 'Rettigheder tildelt dette element',
	'Permissions that inherit this item' => 'Rettigheder som arver fra dette element',
	'Remove' => 'Fjern',
	'Revoke' => 'Tilbagekald',
	'Save' => 'Gem',
	'Select item' => 'Vælg element',
	'System name' => 'Systemnavn',
	'System name cannot be changed after creation.' => 'Systemnavn kan ikke skiftes efter oprettelse.',
	'This item does not have any ancestors.' => 'Dette element har ikke nogen forfædre',
	'This item does not have any descendants.' => 'Dette element har ikke nogen efterkommere.',
	'This user does not have any assignments.' => 'Denne bruger har ikke nogen tildelinger.',
	'Type' => 'Type',
	'User' => 'Bruger',
	'View' => 'Vis',
	'operation|operations' => 'operation|operationer',
	'role|roles' => 'role|roler',
	'task|tasks' => 'opgave|opgaver',
);
